In [78]:
import pandas as pd
import json

# Load the Excel file
file_path = '/Users/tush/Downloads/WTHPA Master Mouse Spreadsheet - Group 7.csv'
df = pd.read_csv(file_path, header=None)

# Inspect the dataframe
print(df.head())

         0          1            2                   3                 4   \
0       NaN        NaN          NaN                 NaN               NaN
1       DOB  2/11/2024  Age (weeks)  Weight lifting (%)  Pellets per lift
2  Training   4/8/2024  8.142857143                 NaN                 1
3  Training   4/9/2024  8.285714286                 NaN                 1
4  Training  4/10/2024  8.428571429                 NaN                 1

              5                   6                  7              8   \
0          F0105                 NaN                NaN          F0106
1  Body Mass (g)  Weight lifting (g)  Remaining pellets  Body Mass (g)
2            NaN                 NaN                NaN            NaN
3            NaN                 NaN                NaN            NaN
4            NaN                 NaN                NaN            NaN

                   9   ...                 19             20  \
0                 NaN  ...                NaN          F0110
1  Weight lifting (g)  ...  Remaining pellets  Body Mass (g)
2                 NaN  ...                NaN            NaN
3                 NaN  ...                NaN            NaN
4                 NaN  ...                NaN            NaN

                   21                 22             23                  24  \
0                 NaN                NaN          F0111                 NaN
1  Weight lifting (g)  Remaining pellets  Body Mass (g)  Weight lifting (g)
2                 NaN                NaN            NaN                 NaN
3                 NaN                NaN            NaN                 NaN
4                 NaN                NaN            NaN                 NaN

                  25             26                  27                 28
0                NaN          F0112                 NaN                NaN
1  Remaining pellets  Body Mass (g)  Weight lifting (g)  Remaining pellets
2                NaN            NaN                 NaN                NaN
3                NaN            NaN                 NaN                NaN
4                NaN            NaN                 NaN                NaN

[5 rows x 29 columns]

In [79]:
df.drop([0], axis=1, inplace=True)
df

,1,2,3,4,5,6,7,8,9,10,...,19,20,21,22,23,24,25,26,27,28
0,NaN,NaN,NaN,NaN,F0105,NaN,NaN,F0106,NaN,NaN,...,NaN,F0110,NaN,NaN,F0111,NaN,NaN,F0112,NaN,NaN
1,2/11/2024,Age (weeks),Weight lifting (%),Pellets per lift,Body Mass (g),Weight lifting (g),Remaining pellets,Body Mass (g),Weight lifting (g),Remaining pellets,...,Remaining pellets,Body Mass (g),Weight lifting (g),Remaining pellets,Body Mass (g),Weight lifting (g),Remaining pellets,Body Mass (g),Weight lifting (g),Remaining pellets
2,4/8/2024,8.142857143,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4/9/2024,8.285714286,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4/10/2024,8.428571429,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,7/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,7/16/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,7/17/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,7/18/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,6/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
for i,c in enumerate(df.iloc[0]):
    print(i,c)

0 nan
1 nan
2 nan
3 nan
4 F0105
5 nan
6 nan
7 F0106
8 nan
9 nan
10 F0107
11 nan
12 nan
13 F0108
14 nan
15 nan
16 F0109
17 nan
18 nan
19 F0110
20 nan
21 nan
22 F0111
23 nan
24 nan
25 F0112
26 nan
27 nan

In [82]:
df=df[[1, 5,6,8,9, 11, 12, 14, 15, 17, 18, 20, 21, 23, 24, 26, 27]]

In [83]:
df

,1,5,6,8,9,11,12,14,15,17,18,20,21,23,24,26,27
0,NaN,F0105,NaN,F0106,NaN,F0107,NaN,F0108,NaN,F0109,NaN,F0110,NaN,F0111,NaN,F0112,NaN
1,2/11/2024,Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g)
2,4/8/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4/9/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4/10/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,7/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,7/16/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,7/17/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,7/18/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,6/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df.iloc[0]

1       NaN
5     F0105
6       NaN
8     F0106
9       NaN
11    F0107
12      NaN
14    F0108
15      NaN
17    F0109
18      NaN
20    F0110
21      NaN
23    F0111
24      NaN
26    F0112
27      NaN
Name: 0, dtype: object

In [85]:
df.columns = df.iloc[0]
df

,NaN,F0105,NaN,F0106,NaN,F0107,NaN,F0108,NaN,F0109,NaN,F0110,NaN,F0111,NaN,F0112,NaN
0,NaN,F0105,NaN,F0106,NaN,F0107,NaN,F0108,NaN,F0109,NaN,F0110,NaN,F0111,NaN,F0112,NaN
1,2/11/2024,Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g)
2,4/8/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4/9/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4/10/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,7/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,7/16/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,7/17/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,7/18/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,6/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
df.drop([0], inplace=True)
df

/var/folders/nq/svc2nf551n74zpynk96y1b7w0000gn/T/ipykernel_8079/729933129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop([0], inplace=True)

,NaN,F0105,NaN,F0106,NaN,F0107,NaN,F0108,NaN,F0109,NaN,F0110,NaN,F0111,NaN,F0112,NaN
1,2/11/2024,Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g)
2,4/8/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4/9/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4/10/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4/11/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,7/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,7/16/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,7/17/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,7/18/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,6/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
cols = df.columns.tolist()
cols[0]='Date'
df.columns = cols
df

,Date,F0105,NaN,F0106,NaN,F0107,NaN,F0108,NaN,F0109,NaN,F0110,NaN,F0111,NaN,F0112,NaN
1,2/11/2024,Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g),Body Mass (g),Weight lifting (g)
2,4/8/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4/9/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4/10/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4/11/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,7/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,7/16/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,7/17/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,7/18/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,6/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
import numpy as np
import math
indices = [i for i, x in enumerate(cols) if type(x) != str and math.isnan(x)]
indices

[2, 4, 6, 8, 10, 12, 14, 16]

In [89]:
df.drop(df.columns[indices], axis=1, inplace=True)
df

/var/folders/nq/svc2nf551n74zpynk96y1b7w0000gn/T/ipykernel_8079/2176549228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(df.columns[indices], axis=1, inplace=True)

,Date,F0105,F0106,F0107,F0108,F0109,F0110,F0111,F0112
1,2/11/2024,Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g)
2,4/8/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4/9/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4/10/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4/11/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
100,7/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,7/16/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,7/17/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,7/18/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,6/15/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
df.dropna(inplace=True)
df

/var/folders/nq/svc2nf551n74zpynk96y1b7w0000gn/T/ipykernel_8079/955798070.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

,Date,F0105,F0106,F0107,F0108,F0109,F0110,F0111,F0112
1,2/11/2024,Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g)
10,4/16/2024,20,20.1,19,20.7,19.8,18.2,18.3,17.9
13,4/19/2024,19.7,20,20.6,21,21.2,19.1,17.2,18.5
17,4/23/2024,20.1,20.4,22.4,21.3,22,18.3,19.3,18.2
20,4/26/2024,21.3,21,22,22.1,23.5,19.1,20.8,19.8
24,4/30/2024,20.9,21,23.2,22,22.7,18.4,20,19.1
27,5/3/2024,21.1,21.6,24.2,22.5,23,18.7,20.1,19.1
31,5/7/2024,21,21.1,24.5,22.3,24.1,18.7,20.6,19.4
34,5/10/2024,21.3,20.9,25,22.6,23.7,18.4,20,18.5
37,5/13/2024,21.8,21.6,24.5,22.6,24,18.7,20.6,19.5
41,5/17/2024,20,21.8,25,22.1,24.5,18.9,20.6,19.2
45,5/21/2024,19.7,22.6,25.7,21,24,19.3,20.8,19

In [91]:
df.set_index('Date', inplace=True)
df

,F0105,F0106,F0107,F0108,F0109,F0110,F0111,F0112
Date,,,,,,,,
2/11/2024,Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g),Body Mass (g)
4/16/2024,20,20.1,19,20.7,19.8,18.2,18.3,17.9
4/19/2024,19.7,20,20.6,21,21.2,19.1,17.2,18.5
4/23/2024,20.1,20.4,22.4,21.3,22,18.3,19.3,18.2
4/26/2024,21.3,21,22,22.1,23.5,19.1,20.8,19.8
4/30/2024,20.9,21,23.2,22,22.7,18.4,20,19.1
5/3/2024,21.1,21.6,24.2,22.5,23,18.7,20.1,19.1
5/7/2024,21,21.1,24.5,22.3,24.1,18.7,20.6,19.4
5/10/2024,21.3,20.9,25,22.6,23.7,18.4,20,18.5
5/13/2024,21.8,21.6,24.5,22.6,24,18.7,20.6,19.5
5/17/2024,20,21.8,25,22.1,24.5,18.9,20.6,19.2
5/21/2024,19.7,22.6,25.7,21,24,19.3,20.8,19

In [92]:
df.drop(df.index[0], inplace=True)
df

/var/folders/nq/svc2nf551n74zpynk96y1b7w0000gn/T/ipykernel_8079/3630692820.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(df.index[0], inplace=True)

          F0105 F0106 F0107 F0108 F0109 F0110 F0111 F0112
Date
4/16/2024    20  20.1    19  20.7  19.8  18.2  18.3  17.9
4/19/2024  19.7    20  20.6    21  21.2  19.1  17.2  18.5
4/23/2024  20.1  20.4  22.4  21.3    22  18.3  19.3  18.2
4/26/2024  21.3    21    22  22.1  23.5  19.1  20.8  19.8
4/30/2024  20.9    21  23.2    22  22.7  18.4    20  19.1
5/3/2024   21.1  21.6  24.2  22.5    23  18.7  20.1  19.1
5/7/2024     21  21.1  24.5  22.3  24.1  18.7  20.6  19.4
5/10/2024  21.3  20.9    25  22.6  23.7  18.4    20  18.5
5/13/2024  21.8  21.6  24.5  22.6    24  18.7  20.6  19.5
5/17/2024    20  21.8    25  22.1  24.5  18.9  20.6  19.2
5/21/2024  19.7  22.6  25.7    21    24  19.3  20.8    19

In [93]:
subjects = df.columns.tolist()
subjects

['F0105', 'F0106', 'F0107', 'F0108', 'F0109', 'F0110', 'F0111', 'F0112']

In [94]:
from datetime import datetime

data = {}
for i,r in df.iterrows():
    # parse date of the format mm/dd/yyyy into datetime object and then convert it to yyyy-mm-dd
    d = datetime.strptime(i, '%m/%d/%Y')
    date = d.strftime('%Y-%m-%d')
    # print(date)
    data[date] = {
        j:{
            "body_mass":str(k),
            "weight_lifted":0,
        }
        for j,k in zip(subjects, r)
    }
    
data

{'2024-04-16': {'F0105': {'body_mass': '20', 'weight_lifted': 0},
  'F0106': {'body_mass': '20.1', 'weight_lifted': 0},
  'F0107': {'body_mass': '19', 'weight_lifted': 0},
  'F0108': {'body_mass': '20.7', 'weight_lifted': 0},
  'F0109': {'body_mass': '19.8', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.2', 'weight_lifted': 0},
  'F0111': {'body_mass': '18.3', 'weight_lifted': 0},
  'F0112': {'body_mass': '17.9', 'weight_lifted': 0}},
 '2024-04-19': {'F0105': {'body_mass': '19.7', 'weight_lifted': 0},
  'F0106': {'body_mass': '20', 'weight_lifted': 0},
  'F0107': {'body_mass': '20.6', 'weight_lifted': 0},
  'F0108': {'body_mass': '21', 'weight_lifted': 0},
  'F0109': {'body_mass': '21.2', 'weight_lifted': 0},
  'F0110': {'body_mass': '19.1', 'weight_lifted': 0},
  'F0111': {'body_mass': '17.2', 'weight_lifted': 0},
  'F0112': {'body_mass': '18.5', 'weight_lifted': 0}},
 '2024-04-23': {'F0105': {'body_mass': '20.1', 'weight_lifted': 0},
  'F0106': {'body_mass': '20.4', 'weight_lifted': 0},
  'F0107': {'body_mass': '22.4', 'weight_lifted': 0},
  'F0108': {'body_mass': '21.3', 'weight_lifted': 0},
  'F0109': {'body_mass': '22', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.3', 'weight_lifted': 0},
  'F0111': {'body_mass': '19.3', 'weight_lifted': 0},
  'F0112': {'body_mass': '18.2', 'weight_lifted': 0}},
 '2024-04-26': {'F0105': {'body_mass': '21.3', 'weight_lifted': 0},
  'F0106': {'body_mass': '21', 'weight_lifted': 0},
  'F0107': {'body_mass': '22', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.1', 'weight_lifted': 0},
  'F0109': {'body_mass': '23.5', 'weight_lifted': 0},
  'F0110': {'body_mass': '19.1', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.8', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.8', 'weight_lifted': 0}},
 '2024-04-30': {'F0105': {'body_mass': '20.9', 'weight_lifted': 0},
  'F0106': {'body_mass': '21', 'weight_lifted': 0},
  'F0107': {'body_mass': '23.2', 'weight_lifted': 0},
  'F0108': {'body_mass': '22', 'weight_lifted': 0},
  'F0109': {'body_mass': '22.7', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.4', 'weight_lifted': 0},
  'F0111': {'body_mass': '20', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.1', 'weight_lifted': 0}},
 '2024-05-03': {'F0105': {'body_mass': '21.1', 'weight_lifted': 0},
  'F0106': {'body_mass': '21.6', 'weight_lifted': 0},
  'F0107': {'body_mass': '24.2', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.5', 'weight_lifted': 0},
  'F0109': {'body_mass': '23', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.7', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.1', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.1', 'weight_lifted': 0}},
 '2024-05-07': {'F0105': {'body_mass': '21', 'weight_lifted': 0},
  'F0106': {'body_mass': '21.1', 'weight_lifted': 0},
  'F0107': {'body_mass': '24.5', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.3', 'weight_lifted': 0},
  'F0109': {'body_mass': '24.1', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.7', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.6', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.4', 'weight_lifted': 0}},
 '2024-05-10': {'F0105': {'body_mass': '21.3', 'weight_lifted': 0},
  'F0106': {'body_mass': '20.9', 'weight_lifted': 0},
  'F0107': {'body_mass': '25', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.6', 'weight_lifted': 0},
  'F0109': {'body_mass': '23.7', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.4', 'weight_lifted': 0},
  'F0111': {'body_mass': '20', 'weight_lifted': 0},
  'F0112': {'body_mass': '18.5', 'weight_lifted': 0}},
 '2024-05-13': {'F0105': {'body_mass': '21.8', 'weight_lifted': 0},
  'F0106': {'body_mass': '21.6', 'weight_lifted': 0},
  'F0107': {'body_mass': '24.5', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.6', 'weight_lifted': 0},
  'F0109': {'body_mass': '24', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.7', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.6', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.5', 'weight_lifted': 0}},
 '2024-05-17': {'F0105': {'body_mass': '20', 'weight_lifted': 0},
  'F0106': {'body_mass': '21.8', 'weight_lifted': 0},
  'F0107': {'body_mass': '25', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.1', 'weight_lifted': 0},
  'F0109': {'body_mass': '24.5', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.9', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.6', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.2', 'weight_lifted': 0}},
 '2024-05-21': {'F0105': {'body_mass': '19.7', 'weight_lifted': 0},
  'F0106': {'body_mass': '22.6', 'weight_lifted': 0},
  'F0107': {'body_mass': '25.7', 'weight_lifted': 0},
  'F0108': {'body_mass': '21', 'weight_lifted': 0},
  'F0109': {'body_mass': '24', 'weight_lifted': 0},
  'F0110': {'body_mass': '19.3', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.8', 'weight_lifted': 0},
  'F0112': {'body_mass': '19', 'weight_lifted': 0}}}

In [95]:
data['meta'] = {
    'subjects':subjects
}
data

{'2024-04-16': {'F0105': {'body_mass': '20', 'weight_lifted': 0},
  'F0106': {'body_mass': '20.1', 'weight_lifted': 0},
  'F0107': {'body_mass': '19', 'weight_lifted': 0},
  'F0108': {'body_mass': '20.7', 'weight_lifted': 0},
  'F0109': {'body_mass': '19.8', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.2', 'weight_lifted': 0},
  'F0111': {'body_mass': '18.3', 'weight_lifted': 0},
  'F0112': {'body_mass': '17.9', 'weight_lifted': 0}},
 '2024-04-19': {'F0105': {'body_mass': '19.7', 'weight_lifted': 0},
  'F0106': {'body_mass': '20', 'weight_lifted': 0},
  'F0107': {'body_mass': '20.6', 'weight_lifted': 0},
  'F0108': {'body_mass': '21', 'weight_lifted': 0},
  'F0109': {'body_mass': '21.2', 'weight_lifted': 0},
  'F0110': {'body_mass': '19.1', 'weight_lifted': 0},
  'F0111': {'body_mass': '17.2', 'weight_lifted': 0},
  'F0112': {'body_mass': '18.5', 'weight_lifted': 0}},
 '2024-04-23': {'F0105': {'body_mass': '20.1', 'weight_lifted': 0},
  'F0106': {'body_mass': '20.4', 'weight_lifted': 0},
  'F0107': {'body_mass': '22.4', 'weight_lifted': 0},
  'F0108': {'body_mass': '21.3', 'weight_lifted': 0},
  'F0109': {'body_mass': '22', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.3', 'weight_lifted': 0},
  'F0111': {'body_mass': '19.3', 'weight_lifted': 0},
  'F0112': {'body_mass': '18.2', 'weight_lifted': 0}},
 '2024-04-26': {'F0105': {'body_mass': '21.3', 'weight_lifted': 0},
  'F0106': {'body_mass': '21', 'weight_lifted': 0},
  'F0107': {'body_mass': '22', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.1', 'weight_lifted': 0},
  'F0109': {'body_mass': '23.5', 'weight_lifted': 0},
  'F0110': {'body_mass': '19.1', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.8', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.8', 'weight_lifted': 0}},
 '2024-04-30': {'F0105': {'body_mass': '20.9', 'weight_lifted': 0},
  'F0106': {'body_mass': '21', 'weight_lifted': 0},
  'F0107': {'body_mass': '23.2', 'weight_lifted': 0},
  'F0108': {'body_mass': '22', 'weight_lifted': 0},
  'F0109': {'body_mass': '22.7', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.4', 'weight_lifted': 0},
  'F0111': {'body_mass': '20', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.1', 'weight_lifted': 0}},
 '2024-05-03': {'F0105': {'body_mass': '21.1', 'weight_lifted': 0},
  'F0106': {'body_mass': '21.6', 'weight_lifted': 0},
  'F0107': {'body_mass': '24.2', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.5', 'weight_lifted': 0},
  'F0109': {'body_mass': '23', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.7', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.1', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.1', 'weight_lifted': 0}},
 '2024-05-07': {'F0105': {'body_mass': '21', 'weight_lifted': 0},
  'F0106': {'body_mass': '21.1', 'weight_lifted': 0},
  'F0107': {'body_mass': '24.5', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.3', 'weight_lifted': 0},
  'F0109': {'body_mass': '24.1', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.7', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.6', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.4', 'weight_lifted': 0}},
 '2024-05-10': {'F0105': {'body_mass': '21.3', 'weight_lifted': 0},
  'F0106': {'body_mass': '20.9', 'weight_lifted': 0},
  'F0107': {'body_mass': '25', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.6', 'weight_lifted': 0},
  'F0109': {'body_mass': '23.7', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.4', 'weight_lifted': 0},
  'F0111': {'body_mass': '20', 'weight_lifted': 0},
  'F0112': {'body_mass': '18.5', 'weight_lifted': 0}},
 '2024-05-13': {'F0105': {'body_mass': '21.8', 'weight_lifted': 0},
  'F0106': {'body_mass': '21.6', 'weight_lifted': 0},
  'F0107': {'body_mass': '24.5', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.6', 'weight_lifted': 0},
  'F0109': {'body_mass': '24', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.7', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.6', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.5', 'weight_lifted': 0}},
 '2024-05-17': {'F0105': {'body_mass': '20', 'weight_lifted': 0},
  'F0106': {'body_mass': '21.8', 'weight_lifted': 0},
  'F0107': {'body_mass': '25', 'weight_lifted': 0},
  'F0108': {'body_mass': '22.1', 'weight_lifted': 0},
  'F0109': {'body_mass': '24.5', 'weight_lifted': 0},
  'F0110': {'body_mass': '18.9', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.6', 'weight_lifted': 0},
  'F0112': {'body_mass': '19.2', 'weight_lifted': 0}},
 '2024-05-21': {'F0105': {'body_mass': '19.7', 'weight_lifted': 0},
  'F0106': {'body_mass': '22.6', 'weight_lifted': 0},
  'F0107': {'body_mass': '25.7', 'weight_lifted': 0},
  'F0108': {'body_mass': '21', 'weight_lifted': 0},
  'F0109': {'body_mass': '24', 'weight_lifted': 0},
  'F0110': {'body_mass': '19.3', 'weight_lifted': 0},
  'F0111': {'body_mass': '20.8', 'weight_lifted': 0},
  'F0112': {'body_mass': '19', 'weight_lifted': 0}},
 'meta': {'subjects': ['F0105',
   'F0106',
   'F0107',
   'F0108',
   'F0109',
   'F0110',
   'F0111',
   'F0112']}}

In [96]:
import json
with open('/Users/tush/Grad School/CMRG Lab/monitor/media/mice_data/group_7.json', 'w') as f:
    json.dump(data, f, indent=4)